-- V3.1 Slice 9 — audit actions for admin archive/deactivate (no data deletes)

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EVENT_RESTORED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'GASTRO_PROFILE_SUSPENDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'GASTRO_PROFILE_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RENTAL_LOCATION_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RENTAL_LOCATION_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXCURSION_OPERATOR_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXCURSION_OPERATOR_ACTIVATED';
