-- AlterEnum
ALTER TYPE "NotificationKind" ADD VALUE 'TICKET_TRANSFER_ACCEPTED';
ALTER TYPE "NotificationKind" ADD VALUE 'TICKET_TRANSFER_REJECTED';
ALTER TYPE "NotificationKind" ADD VALUE 'TICKET_TRANSFER_CANCELLED';
