/**
 * V3.1 Etapa 8 — Ticket date change policy constants (Slice 8.1).
 * See docs/tickets/TICKET_DATE_CHANGE_POLICY.md
 */

/** Minimum hours before occurrence start (origin or destination) to allow a change. */
export const TICKET_DATE_CHANGE_WINDOW_HOURS = 24;

/** Block reasons returned by eligibility API (stable codes for UI). */
export const TICKET_DATE_CHANGE_BLOCK_REASON = {
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  NOT_OWNER: 'NOT_OWNER',
  TICKET_USED: 'TICKET_USED',
  TICKET_REVOKED: 'TICKET_REVOKED',
  TICKET_EXPIRED: 'TICKET_EXPIRED',
  TRANSFER_PENDING: 'TRANSFER_PENDING',
  SINGLE_DATE_EVENT: 'SINGLE_DATE_EVENT',
  NO_OCCURRENCE: 'NO_OCCURRENCE',
  SAME_OCCURRENCE: 'SAME_OCCURRENCE',
  OCCURRENCE_NOT_FOUND: 'OCCURRENCE_NOT_FOUND',
  OCCURRENCE_INACTIVE: 'OCCURRENCE_INACTIVE',
  OCCURRENCE_SOLD_OUT: 'OCCURRENCE_SOLD_OUT',
  NO_COMPATIBLE_TICKET_TYPE: 'NO_COMPATIBLE_TICKET_TYPE',
  PRICE_MISMATCH: 'PRICE_MISMATCH',
  OUTSIDE_TIME_WINDOW: 'OUTSIDE_TIME_WINDOW',
  PENDING_REQUEST_EXISTS: 'PENDING_REQUEST_EXISTS',
} as const;

export type TicketDateChangeBlockReason =
  (typeof TICKET_DATE_CHANGE_BLOCK_REASON)[keyof typeof TICKET_DATE_CHANGE_BLOCK_REASON];
