-- Review & dispute notification kinds (Reviews V2 slice 5)
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'REVIEW_RECEIVED';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'REVIEW_OFFICIAL_REPLY';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'REVIEW_DISPUTE_CREATED';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'REVIEW_DISPUTE_ACCEPTED';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'REVIEW_DISPUTE_REJECTED';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'REVIEW_MODERATION_HIDDEN';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'REVIEW_MODERATION_RESTORED';
