/**
 * API error codes — shared across API and clients
 */

export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_ALREADY_REVOKED: 'TICKET_ALREADY_REVOKED',
  TICKET_NOT_TRANSFERABLE: 'TICKET_NOT_TRANSFERABLE',
  TRANSFER_CONFLICT: 'TRANSFER_CONFLICT',
  EVENT_CAPACITY_EXCEEDED: 'EVENT_CAPACITY_EXCEEDED',
  CAPACITY_BELOW_CURRENT_USAGE: 'CAPACITY_BELOW_CURRENT_USAGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',
  ORDER_EXPIRED: 'ORDER_EXPIRED',
  ASSOCIATION_BLOCKED: 'ASSOCIATION_BLOCKED',
  ASSOCIATION_INVALID_TRANSITION: 'ASSOCIATION_INVALID_TRANSITION',
  /** Relación productora–referidor no está ACTIVE; no se puede asignar a evento */
  ASSOCIATION_NOT_ACTIVE: 'ASSOCIATION_NOT_ACTIVE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
