/**
 * API error codes — shared across API and clients
 */

export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_ALREADY_REVOKED: 'TICKET_ALREADY_REVOKED',
  TICKET_NOT_TRANSFERABLE: 'TICKET_NOT_TRANSFERABLE',
  TRANSFER_CONFLICT: 'TRANSFER_CONFLICT',
  EVENT_CAPACITY_EXCEEDED: 'EVENT_CAPACITY_EXCEEDED',
  CAPACITY_BELOW_CURRENT_USAGE: 'CAPACITY_BELOW_CURRENT_USAGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',
  ORDER_EXPIRED: 'ORDER_EXPIRED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
