/**
 * API error codes — shared across API and clients
 */

export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_ALREADY_REVOKED: 'TICKET_ALREADY_REVOKED',
  TICKET_NOT_TRANSFERABLE: 'TICKET_NOT_TRANSFERABLE',
  NOT_TICKET_OWNER: 'NOT_TICKET_OWNER',
  TICKET_ALREADY_USED: 'TICKET_ALREADY_USED',
  TICKET_REVOKED: 'TICKET_REVOKED',
  TICKET_EXPIRED: 'TICKET_EXPIRED',
  TRANSFER_ALREADY_PENDING: 'TRANSFER_ALREADY_PENDING',
  TRANSFER_CONFLICT: 'TRANSFER_CONFLICT',
  EVENT_CAPACITY_EXCEEDED: 'EVENT_CAPACITY_EXCEEDED',
  CAPACITY_BELOW_CURRENT_USAGE: 'CAPACITY_BELOW_CURRENT_USAGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ORDER_EXPIRED: 'ORDER_EXPIRED',
  ASSOCIATION_BLOCKED: 'ASSOCIATION_BLOCKED',
  ASSOCIATION_INVALID_TRANSITION: 'ASSOCIATION_INVALID_TRANSITION',
  /** Relación productora–referidor no está ACTIVE; no se puede asignar a evento */
  ASSOCIATION_NOT_ACTIVE: 'ASSOCIATION_NOT_ACTIVE',
  REFERRAL_PROPOSAL_DUPLICATE: 'REFERRAL_PROPOSAL_DUPLICATE',
  REFERRAL_PROPOSAL_NOT_PENDING: 'REFERRAL_PROPOSAL_NOT_PENDING',
  REFERRAL_PROPOSAL_EXPIRED: 'REFERRAL_PROPOSAL_EXPIRED',
  REFERRAL_PAYMENT_COMMISSION_NOT_ELIGIBLE: 'REFERRAL_PAYMENT_COMMISSION_NOT_ELIGIBLE',
  REFERRAL_PAYMENT_COMMISSION_ALREADY_REQUESTED: 'REFERRAL_PAYMENT_COMMISSION_ALREADY_REQUESTED',
  REFERRAL_PAYMENT_REQUEST_NOT_CANCELLABLE: 'REFERRAL_PAYMENT_REQUEST_NOT_CANCELLABLE',
  REFERRAL_PAYMENT_INVALID_STATUS_TRANSITION: 'REFERRAL_PAYMENT_INVALID_STATUS_TRANSITION',
  LEGAL_ACCEPTANCE_REQUIRED: 'LEGAL_ACCEPTANCE_REQUIRED',
  LEGAL_DOCUMENT_NOT_PUBLISHED: 'LEGAL_DOCUMENT_NOT_PUBLISHED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
